services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cleaner_dev
      PGDATA: /data/postgres
    volumes:
      - database:/data/postgres
    restart: unless-stopped
    ports:
      - 5432:5432

  app:
    build:
      context: .
    depends_on:
      - database
    environment:
      DATABASE_URL: ecto://postgres:postgres@database/cleaner_dev
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
    restart: unless-stopped
    profiles:
      - app

volumes:
  database:
