services:
  database_dev:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cleaner_dev
      PGDATA: /data/postgres
    volumes:
      - database_dev:/data/postgres
    restart: unless-stopped
    ports:
      - 5432:5432

volumes:
  database_dev:

networks:
  default:
    name: "cleaner_dev_default"