services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cleaner_prod
      PGDATA: /data/postgres
    volumes:
      - database:/data/postgres
    restart: unless-stopped

  app:
    build:
      context: .
    depends_on:
      - database
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
    restart: unless-stopped

volumes:
  database:
